# Generated by Django 4.1.3 on 2024-08-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_is_active_investmentplan_min_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='interest_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment')),
            ],
        ),
    ]
