# Generated by Django 4.1.3 on 2024-08-11 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_paradisecoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coins_acquired', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ParadiseCoin',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='brl_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='coin_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
