# Generated by Django 4.1.3 on 2024-08-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParadiseCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_supply', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
            ],
        ),
    ]
