# Generated by Django 4.1.3 on 2024-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradisecoin',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
